# Generated by Django 5.1.6 on 2025-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='platform',
            field=models.CharField(max_length=20),
        ),
    ]
